# Generated by Django 6.0 on 2025-12-21 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='成就名稱')),
                ('description', models.TextField(max_length=300, verbose_name='成就描述')),
                ('icon', models.CharField(default='🏆', max_length=10, verbose_name='圖示')),
                ('category', models.CharField(choices=[('activity', '活躍度'), ('learning', '學習'), ('social', '社交'), ('contribution', '貢獻'), ('special', '特殊')], default='activity', max_length=20, verbose_name='分類')),
                ('points', models.IntegerField(default=10, verbose_name='獲得積分')),
                ('condition_type', models.CharField(blank=True, max_length=50, verbose_name='條件類型')),
                ('condition_value', models.IntegerField(default=0, verbose_name='條件數值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '成就',
                'verbose_name_plural': '成就',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LearningCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='課程名稱')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='課程描述')),
                ('color', models.CharField(default='#4CAF50', max_length=7, verbose_name='進度條顏色')),
                ('total_lessons', models.IntegerField(default=10, verbose_name='總課程數')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '學習課程',
                'verbose_name_plural': '學習課程',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('post', '發表文章'), ('comment', '發表評論'), ('like', '按讚'), ('achievement', '獲得成就'), ('level_up', '等級提升'), ('course', '完成課程')], max_length=20, verbose_name='活動類型')),
                ('title', models.CharField(max_length=200, verbose_name='活動標題')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='活動描述')),
                ('icon', models.CharField(default='📝', max_length=10, verbose_name='圖示')),
                ('related_object_id', models.IntegerField(blank=True, null=True, verbose_name='相關物件ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '使用者活動',
                'verbose_name_plural': '使用者活動',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='技能名稱')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('users', models.ManyToManyField(blank=True, related_name='skills', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '技能標籤',
                'verbose_name_plural': '技能標籤',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='個人簡介')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='頭像')),
                ('school', models.CharField(blank=True, max_length=100, verbose_name='學校')),
                ('grade', models.CharField(blank=True, max_length=50, verbose_name='年級')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='地點')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('level', models.CharField(choices=[('Bronze', '銅牌'), ('Silver', '銀牌'), ('Gold', '金牌'), ('Platinum', '白金'), ('Diamond', '鑽石')], default='Bronze', max_length=20, verbose_name='會員等級')),
                ('points', models.IntegerField(default=0, verbose_name='積分')),
                ('website', models.URLField(blank=True, verbose_name='個人網站')),
                ('github', models.CharField(blank=True, max_length=100, verbose_name='GitHub')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '使用者資料',
                'verbose_name_plural': '使用者資料',
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='追蹤時間')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='追蹤者')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='被追蹤者')),
            ],
            options={
                'verbose_name': '追蹤關係',
                'verbose_name_plural': '追蹤關係',
                'ordering': ['-created_at'],
                'unique_together': {('follower', 'following')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, verbose_name='解鎖時間')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.achievement', verbose_name='成就')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '使用者成就',
                'verbose_name_plural': '使用者成就',
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='UserCourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_lessons', models.IntegerField(default=0, verbose_name='已完成課程數')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='最後活動時間')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.learningcourse', verbose_name='課程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '使用者課程進度',
                'verbose_name_plural': '使用者課程進度',
                'ordering': ['-last_activity'],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
