# Generated by Django 6.0 on 2025-12-21 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_options_alter_article_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleReadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_read_at', models.DateTimeField(auto_now_add=True, verbose_name='首次閱讀時間')),
                ('last_read_at', models.DateTimeField(auto_now=True, verbose_name='最後閱讀時間')),
                ('read_count', models.IntegerField(default=1, verbose_name='閱讀次數')),
                ('reading_time_seconds', models.IntegerField(default=0, verbose_name='閱讀時長(秒)')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_records', to='blog.article', verbose_name='文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_history', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '文章閱讀記錄',
                'verbose_name_plural': '文章閱讀記錄',
                'ordering': ['-last_read_at'],
                'unique_together': {('user', 'article')},
            },
        ),
    ]
