# Generated by Django 6.0 on 2025-12-22 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='主旨')),
                ('content', models.TextField(verbose_name='內容')),
                ('is_read', models.BooleanField(default=False, verbose_name='已讀')),
                ('sender_deleted', models.BooleanField(default=False, verbose_name='寄件者已刪除')),
                ('recipient_deleted', models.BooleanField(default=False, verbose_name='收件者已刪除')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='閱讀時間')),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.message', verbose_name='回覆訊息')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='收件者')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='寄件者')),
            ],
            options={
                'verbose_name': '私人訊息',
                'verbose_name_plural': '私人訊息',
                'ordering': ['-created_at'],
            },
        ),
    ]
