# Generated by Django 6.0 on 2025-12-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_tag_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_recalled',
            field=models.BooleanField(default=False, verbose_name='已收回'),
        ),
        migrations.AddField(
            model_name='message',
            name='recalled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='收回時間'),
        ),
    ]
