# Generated by Django 6.0 on 2025-12-24 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_message_is_recalled_message_recalled_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publish_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='排程發布時間'),
        ),
        migrations.AddField(
            model_name='article',
            name='reading_time',
            field=models.IntegerField(default=0, verbose_name='閱讀時間(分鐘)'),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '已發布'), ('scheduled', '已排程')], default='published', max_length=20, verbose_name='狀態'),
        ),
        migrations.CreateModel(
            name='ArticleShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('line', 'LINE'), ('copy', '複製連結'), ('other', '其他')], max_length=20, verbose_name='分享平台')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP位址')),
                ('shared_at', models.DateTimeField(auto_now_add=True, verbose_name='分享時間')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='blog.article', verbose_name='文章')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_shares', to=settings.AUTH_USER_MODEL, verbose_name='分享者')),
            ],
            options={
                'verbose_name': '文章分享',
                'verbose_name_plural': '文章分享',
                'ordering': ['-shared_at'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏時間')),
                ('note', models.TextField(blank=True, verbose_name='筆記')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='blog.article', verbose_name='文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='收藏者')),
            ],
            options={
                'verbose_name': '書籤',
                'verbose_name_plural': '書籤',
                'ordering': ['-created_at'],
                'unique_together': {('article', 'user')},
            },
        ),
    ]
