# Generated by Django 6.0 on 2025-12-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_article_publish_at_article_reading_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='draft_content',
            field=models.TextField(blank=True, null=True, verbose_name='草稿內容'),
        ),
        migrations.AddField(
            model_name='article',
            name='draft_tags_json',
            field=models.TextField(blank=True, null=True, verbose_name='草稿標籤(JSON)'),
        ),
        migrations.AddField(
            model_name='article',
            name='draft_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='草稿標題'),
        ),
        migrations.AddField(
            model_name='article',
            name='draft_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='草稿更新時間'),
        ),
        migrations.AddField(
            model_name='article',
            name='has_draft',
            field=models.BooleanField(default=False, verbose_name='有未發布的草稿'),
        ),
    ]
