# Generated by Django 6.0 on 2025-12-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_article_draft_content_article_draft_tags_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='頭像更新時間'),
        ),
    ]
