# Generated by Django 6.0 on 2025-12-25 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_userprofile_avatar_updated_at'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_comment_notifications', models.BooleanField(default=True, verbose_name='留言通知')),
                ('enable_like_notifications', models.BooleanField(default=True, verbose_name='按讚通知')),
                ('enable_follower_notifications', models.BooleanField(default=True, verbose_name='追蹤者通知')),
                ('enable_message_notifications', models.BooleanField(default=True, verbose_name='私訊通知')),
                ('enable_share_notifications', models.BooleanField(default=True, verbose_name='分享通知')),
                ('enable_email_notifications', models.BooleanField(default=False, verbose_name='Email 通知')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '通知偏好',
                'verbose_name_plural': '通知偏好',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('comment', '留言'), ('like', '按讚'), ('follower', '新追蹤者'), ('message', '私訊'), ('share', '分享')], max_length=20, verbose_name='通知類型')),
                ('message', models.TextField(verbose_name='通知內容')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='連結')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已讀')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='已讀時間')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='發送者')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收者')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='blog_notifi_user_id_e659d5_idx'), models.Index(fields=['user', 'is_read'], name='blog_notifi_user_id_25043d_idx')],
            },
        ),
    ]
