# Generated by Django 6.0 on 2025-12-25 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_notificationpreference_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='公告標題')),
                ('content', models.TextField(verbose_name='公告內容')),
                ('priority', models.CharField(choices=[('low', '低'), ('normal', '一般'), ('high', '高'), ('urgent', '緊急')], default='normal', max_length=20, verbose_name='優先級')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='置頂')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='過期時間')),
                ('views_count', models.IntegerField(default=0, verbose_name='瀏覽數')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='發布時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='發布者')),
            ],
            options={
                'verbose_name': '系統公告',
                'verbose_name_plural': '系統公告',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_title', models.CharField(max_length=100, verbose_name='修改前標題')),
                ('new_title', models.CharField(max_length=100, verbose_name='修改後標題')),
                ('previous_content', models.TextField(verbose_name='修改前內容')),
                ('new_content', models.TextField(verbose_name='修改後內容')),
                ('edit_summary', models.CharField(blank=True, max_length=200, verbose_name='編輯摘要')),
                ('edited_at', models.DateTimeField(auto_now_add=True, verbose_name='編輯時間')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='blog.article', verbose_name='文章')),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_edits', to=settings.AUTH_USER_MODEL, verbose_name='編輯者')),
            ],
            options={
                'verbose_name': '文章編輯歷史',
                'verbose_name_plural': '文章編輯歷史',
                'ordering': ['-edited_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='活動標題')),
                ('description', models.TextField(verbose_name='活動描述')),
                ('event_type', models.CharField(choices=[('announcement', '公告'), ('online_event', '線上活動'), ('course', '課程'), ('competition', '競賽'), ('meetup', '聚會')], max_length=20, verbose_name='活動類型')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='event_covers/', verbose_name='封面圖片')),
                ('start_time', models.DateTimeField(verbose_name='開始時間')),
                ('end_time', models.DateTimeField(verbose_name='結束時間')),
                ('registration_deadline', models.DateTimeField(blank=True, null=True, verbose_name='報名截止時間')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='地點')),
                ('online_link', models.URLField(blank=True, max_length=500, verbose_name='線上連結')),
                ('max_participants', models.IntegerField(blank=True, null=True, verbose_name='參與人數上限')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已發布'), ('ongoing', '進行中'), ('completed', '已結束'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='狀態')),
                ('views_count', models.IntegerField(default=0, verbose_name='瀏覽數')),
                ('participants_count', models.IntegerField(default=0, verbose_name='參與人數')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='組織者')),
            ],
            options={
                'verbose_name': '活動/公告',
                'verbose_name_plural': '活動/公告',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', '已報名'), ('confirmed', '已確認'), ('attended', '已參加'), ('cancelled', '已取消')], default='registered', max_length=20, verbose_name='狀態')),
                ('note', models.TextField(blank=True, max_length=500, verbose_name='備註')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='報名時間')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_records', to='blog.event', verbose_name='活動')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to=settings.AUTH_USER_MODEL, verbose_name='參與者')),
            ],
            options={
                'verbose_name': '活動參與者',
                'verbose_name_plural': '活動參與者',
                'ordering': ['-registered_at'],
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(related_name='joined_events', through='blog.EventParticipant', to=settings.AUTH_USER_MODEL, verbose_name='參與者'),
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', '群組擁有者'), ('admin', '管理員'), ('moderator', '版主'), ('member', '成員')], default='member', max_length=20, verbose_name='角色')),
                ('join_method', models.CharField(choices=[('created', '創建'), ('joined', '主動加入'), ('invited', '被邀請')], default='joined', max_length=20, verbose_name='加入方式')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入時間')),
                ('posts_count', models.IntegerField(default=0, verbose_name='發文數')),
                ('comments_count', models.IntegerField(default=0, verbose_name='留言數')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '群組成員',
                'verbose_name_plural': '群組成員',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='群組名稱')),
                ('description', models.TextField(max_length=500, verbose_name='群組描述')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='group_covers/', verbose_name='封面圖片')),
                ('group_type', models.CharField(choices=[('public', '公開群組'), ('private', '私密群組'), ('invite_only', '邀請制群組')], default='public', max_length=20, verbose_name='群組類型')),
                ('tags', models.CharField(blank=True, help_text='用逗號分隔多個標籤', max_length=200, verbose_name='標籤')),
                ('member_count', models.IntegerField(default=1, verbose_name='成員數量')),
                ('post_count', models.IntegerField(default=0, verbose_name='文章數量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL, verbose_name='創建者')),
                ('members', models.ManyToManyField(related_name='joined_groups', through='blog.GroupMembership', to=settings.AUTH_USER_MODEL, verbose_name='成員')),
            ],
            options={
                'verbose_name': '使用者群組',
                'verbose_name_plural': '使用者群組',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('discussion', '討論'), ('question', '提問'), ('announcement', '公告'), ('share', '分享')], default='discussion', max_length=20, verbose_name='文章類型')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('content', models.TextField(verbose_name='內容')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='置頂')),
                ('views_count', models.IntegerField(default=0, verbose_name='瀏覽數')),
                ('likes_count', models.IntegerField(default=0, verbose_name='按讚數')),
                ('comments_count', models.IntegerField(default=0, verbose_name='留言數')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_posts', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.usergroup', verbose_name='所屬群組')),
            ],
            options={
                'verbose_name': '群組文章',
                'verbose_name_plural': '群組文章',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='blog.usergroup', verbose_name='群組'),
        ),
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='blog.usergroup', verbose_name='關聯群組'),
        ),
        migrations.CreateModel(
            name='ArticleCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', '擁有者'), ('editor', '編輯者'), ('viewer', '檢視者')], default='editor', max_length=20, verbose_name='角色')),
                ('permission', models.CharField(choices=[('read', '僅讀取'), ('comment', '可留言'), ('edit', '可編輯'), ('full', '完全控制')], default='edit', max_length=20, verbose_name='權限')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='已接受邀請')),
                ('invited_at', models.DateTimeField(auto_now_add=True, verbose_name='邀請時間')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='接受時間')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='blog.article', verbose_name='文章')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaboration_invitations_sent', to=settings.AUTH_USER_MODEL, verbose_name='邀請者')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborated_articles', to=settings.AUTH_USER_MODEL, verbose_name='協作者')),
            ],
            options={
                'verbose_name': '文章協作者',
                'verbose_name_plural': '文章協作者',
                'ordering': ['-invited_at'],
                'unique_together': {('article', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mention_type', models.CharField(choices=[('article', '文章'), ('comment', '留言'), ('message', '訊息')], max_length=20, verbose_name='提及類型')),
                ('context', models.TextField(blank=True, max_length=500, verbose_name='提及內容')),
                ('is_read', models.BooleanField(default=False, verbose_name='已讀')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提及時間')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='blog.article', verbose_name='相關文章')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='blog.comment', verbose_name='相關留言')),
                ('mentioned_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions_received', to=settings.AUTH_USER_MODEL, verbose_name='被提及使用者')),
                ('mentioning_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions_made', to=settings.AUTH_USER_MODEL, verbose_name='提及者')),
            ],
            options={
                'verbose_name': '提及',
                'verbose_name_plural': '提及',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mentioned_user', '-created_at'], name='blog_mentio_mention_0e4528_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('group', 'user')},
        ),
    ]
