# Generated by Django 6.0 on 2025-12-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_announcement_articleedithistory_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='enable_mention_notifications',
            field=models.BooleanField(default=True, verbose_name='提及通知'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment', '留言'), ('like', '按讚'), ('follower', '新追蹤者'), ('message', '私訊'), ('share', '分享'), ('mention', '提及')], max_length=20, verbose_name='通知類型'),
        ),
    ]
