# Generated by Django 6.0 on 2025-12-26 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_notificationpreference_enable_mention_notifications_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='訊息內容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='發送時間')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已讀')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='已讀時間')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='接收者')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='發送者')),
            ],
            options={
                'verbose_name': '即時聊天訊息',
                'verbose_name_plural': '即時聊天訊息',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender', 'recipient', '-created_at'], name='blog_chatme_sender__ea319e_idx'), models.Index(fields=['recipient', 'is_read'], name='blog_chatme_recipie_d3ccd8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('last_message_at', models.DateTimeField(auto_now=True, verbose_name='最後訊息時間')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms_as_user1', to=settings.AUTH_USER_MODEL, verbose_name='用戶1')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms_as_user2', to=settings.AUTH_USER_MODEL, verbose_name='用戶2')),
            ],
            options={
                'verbose_name': '聊天室',
                'verbose_name_plural': '聊天室',
                'ordering': ['-last_message_at'],
                'constraints': [models.UniqueConstraint(fields=('user1', 'user2'), name='unique_chat_room')],
            },
        ),
    ]
