# Generated by Django 6.0 on 2025-12-26 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_chatmessage_chatroom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(unique=True, verbose_name='推播端點')),
                ('p256dh', models.CharField(max_length=255, verbose_name='P256DH 密鑰')),
                ('auth', models.CharField(max_length=255, verbose_name='Auth 密鑰')),
                ('user_agent', models.TextField(blank=True, verbose_name='用戶代理')),
                ('device_type', models.CharField(blank=True, choices=[('desktop', '桌面'), ('mobile', '手機'), ('tablet', '平板')], max_length=20, verbose_name='裝置類型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='訂閱時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最後使用時間')),
                ('failure_count', models.IntegerField(default=0, verbose_name='失敗次數')),
                ('last_failure_at', models.DateTimeField(blank=True, null=True, verbose_name='最後失敗時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': 'Web Push 訂閱',
                'verbose_name_plural': 'Web Push 訂閱',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='blog_pushsu_user_id_2c76b4_idx'), models.Index(fields=['endpoint'], name='blog_pushsu_endpoin_0cc0fd_idx')],
            },
        ),
    ]
