# Generated by Django 6.0 on 2025-12-26 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_pushsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200, verbose_name='搜尋關鍵字')),
                ('search_type', models.CharField(choices=[('article', '文章'), ('tag', '標籤'), ('author', '作者'), ('all', '全部')], default='article', max_length=20, verbose_name='搜尋類型')),
                ('results_count', models.IntegerField(default=0, verbose_name='結果數量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='搜尋時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '搜尋歷史',
                'verbose_name_plural': '搜尋歷史',
                'db_table': 'blog_search_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='blog_search_user_id_f2f4a9_idx'), models.Index(fields=['query'], name='blog_search_query_5dff97_idx')],
            },
        ),
    ]
