# Generated by Django 6.0 on 2025-12-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_searchhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment', '留言'), ('like', '按讚'), ('follower', '新追蹤者'), ('message', '私訊'), ('share', '分享'), ('mention', '提及'), ('user_report', '用戶舉報'), ('system_warning', '系統警告'), ('data_change', '數據異動'), ('security_alert', '安全警報'), ('system_error', '系統錯誤')], max_length=20, verbose_name='通知類型'),
        ),
    ]
