# Generated by Django 6.0 on 2025-12-28 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_notification_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP 地址')),
                ('reason', models.TextField(verbose_name='封鎖原因')),
                ('blocked_at', models.DateTimeField(auto_now_add=True, verbose_name='封鎖時間')),
                ('unblock_at', models.DateTimeField(blank=True, null=True, verbose_name='解除封鎖時間')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('blocked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_ips', to=settings.AUTH_USER_MODEL, verbose_name='封鎖者')),
            ],
            options={
                'verbose_name': 'IP 黑名單',
                'verbose_name_plural': 'IP 黑名單',
                'ordering': ['-blocked_at'],
            },
        ),
        migrations.CreateModel(
            name='IPWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP 地址')),
                ('description', models.CharField(max_length=200, verbose_name='描述')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='添加時間')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whitelisted_ips', to=settings.AUTH_USER_MODEL, verbose_name='添加者')),
            ],
            options={
                'verbose_name': 'IP 白名單',
                'verbose_name_plural': 'IP 白名單',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150, verbose_name='用戶名')),
                ('ip_address', models.GenericIPAddressField(db_index=True, verbose_name='IP 地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('attempt_type', models.CharField(choices=[('success', '成功'), ('failed', '失敗')], db_index=True, max_length=10, verbose_name='嘗試類型')),
                ('failure_reason', models.CharField(blank=True, max_length=200, verbose_name='失敗原因')),
                ('attempted_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='嘗試時間')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='國家')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='城市')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '登入嘗試',
                'verbose_name_plural': '登入嘗試',
                'ordering': ['-attempted_at'],
                'indexes': [models.Index(fields=['ip_address', '-attempted_at'], name='blog_logina_ip_addr_62af71_idx'), models.Index(fields=['username', '-attempted_at'], name='blog_logina_usernam_e1e315_idx'), models.Index(fields=['attempt_type', '-attempted_at'], name='blog_logina_attempt_1dc166_idx')],
            },
        ),
    ]
