"""
Blog app 的 views 模組
將各個 views 模組的函數匯入，讓外部可以直接從 views 引用
"""

# 文章相關 views
from .article_views import (
    home,
    about,
    article_detail,
    article_create,
    article_edit,
    article_delete,
    draft_publish,
    draft_discard,
    article_like,
    article_bookmark,
    article_share,
    article_autosave,
    my_articles,
    my_bookmarks,
    my_drafts,
    comment_delete,
    tags_list,
    tag_articles,
    advanced_search,
    search_suggestions,
    quick_search,
    get_similar_articles_api,
    get_personalized_recommendations_api,
    get_recommended_articles_api,
    personalized_feed,
    get_search_history,
    clear_search_history,
    delete_search_item,
    export_article_markdown
)

# 會員相關 views
from .member_views import (
    member,
    member_edit,
    member_profile,
    member_activities,
    member_achievements,
    learning_progress,
    member_articles,
    member_comments,
    user_login,
    user_register,
    user_logout,
    edit_skills,
    change_password,
    follow_user,
    followers_list,
    following_list,
    get_user_api,
    get_chat_list_api,
    subscribe_push,
    unsubscribe_push,
    test_push_notification_view
)

# 訊息相關 views
from .message_views import (
    inbox,
    outbox,
    message_compose,
    message_detail,
    message_delete,
    mark_all_read,
    message_recall,
    bulk_mark_read,
    bulk_delete,
    outbox_bulk_delete
)

# 通知相關 views
from .notification_views import (
    notifications_center,
    notification_mark_read,
    notification_mark_all_read,
    notification_delete,
    notification_delete_all_read,
    notification_count,
    notification_preferences
)

# 社群互動相關 views
from .social_views import (
    mention_list,
    mention_count,
    search_users_for_mention,
    article_collaborators,
    invite_collaborator,
    accept_collaboration,
    remove_collaborator,
    article_edit_history,
    group_list,
    group_create,
    group_detail,
    group_join,
    group_leave,
    group_post_create,
    group_post_detail,
    group_members,
    event_list,
    event_detail,
    event_create,
    event_register,
    event_cancel_registration,
    announcement_list,
    announcement_detail,
    my_groups,
    my_events,
)

__all__ = [
    # 文章相關
    'home',
    'about',
    'article_detail',
    'article_create',
    'article_edit',
    'article_delete',
    'draft_publish',
    'draft_discard',
    'article_like',
    'article_bookmark',
    'article_share',
    'article_autosave',
    'my_articles',
    'my_bookmarks',
    'my_drafts',
    'comment_delete',
    'tags_list',
    'tag_articles',
    'advanced_search',
    'search_suggestions',
    'quick_search',
    'get_similar_articles_api',
    'get_personalized_recommendations_api',
    'get_recommended_articles_api',
    'personalized_feed',
    'get_search_history',
    'clear_search_history',
    'delete_search_item',
    'export_article_markdown',
    # 會員相關
    'member',
    'member_edit',
    'member_profile',
    'member_activities',
    'member_achievements',
    'learning_progress',
    'member_articles',
    'member_comments',
    'user_login',
    'user_register',
    'user_logout',
    'edit_skills',
    'change_password',
    'follow_user',
    'followers_list',
    'following_list',
    'get_user_api',
    'get_chat_list_api',
    'subscribe_push',
    'unsubscribe_push',
    'test_push_notification_view',
    # 訊息相關
    'inbox',
    'outbox',
    'message_compose',
    'message_detail',
    'message_delete',
    'mark_all_read',
    'message_recall',
    'bulk_mark_read',
    'bulk_delete',
    'outbox_bulk_delete',
    # 通知相關
    'notifications_center',
    'notification_mark_read',
    'notification_mark_all_read',
    'notification_delete',
    'notification_delete_all_read',
    'notification_count',
    'notification_preferences',
    # 社群互動相關
    'mention_list',
    'mention_count',
    'search_users_for_mention',
    'article_collaborators',
    'invite_collaborator',
    'accept_collaboration',
    'remove_collaborator',
    'article_edit_history',
    'group_list',
    'group_create',
    'group_detail',
    'group_join',
    'group_leave',
    'group_post_create',
    'group_post_detail',
    'group_members',
    'event_list',
    'event_detail',
    'event_create',
    'event_register',
    'event_cancel_registration',
    'announcement_list',
    'announcement_detail',
    'my_groups',
    'my_events',
]
